### <span style="color:red">**SPRINT 10 PYTHON:**</span> <span style="color:green">**LIMPIEZA Y ANALÍTICA DE DATOS**</span>

# **Nivel 1**

#### 1.1
-Importa como un DataFrame el archivo sprint10.xlsx.  
-Ordena el DataFrame por el país de origen. En caso de empate, ordena por el nombre de la ciudad.
-Muestra las primeras 10 filas.  
-Adicionalmente, realiza un print donde compruebe que el DNI sólo tiene valores únicos.

In [151]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.expand_frame_repr", False) # evita el salto de columnas
pd.set_option("display.max_colwidth", 30)

In [ ]:
df_sprint10 = pd.read_excel("sprint10.xlsx", index_col=0, header=3)
print(df_sprint10) # Con df_sprint10 (o display(df) ) en .ipynb de VS Code, versión enriquecida html

         Nom           Cognoms        DNI País d'origen     Ciutat  Dia de Naixement  Mes de Naixement  Any de Naixement Gènere Salari mensual  Fills  No Fills Grup Professional
0       Inês    Ferreira Silva  16928694K      Portugal     Lisboa                25                 2              1953      D        1.144 €    NaN       1.0            Grup B
1      Clara  Sánchez Martínez  27724652S       Espanya  Barcelona                18                 3              1996      D        1.253 €    1.0       NaN            Grup A
2     Fatima             Fassi  38141675A        Marroc      Rabat                 6                11              2005      A        1.441 €    1.0       NaN            Grup A
3    Khadija   Bennani Bennani  59157262R        Marroc      Rabat                20                 1              1995      D        1.944 €    NaN       1.0            Grup B
4       Toni    Sánchez García  69630528M       Espanya  Barcelona                 9                 8              1999      H        1.043 €    NaN       1.0            Grup A
..       ...               ...        ...           ...        ...               ...               ...               ...    ...            ...    ...       ...               ...
995    Marta     Ferrer Ferrer  25161375F       Espanya    Sevilla                 1                 6              1951      D        1.216 €    NaN       1.0            Grup B
996     Joan            García  52145541P       Espanya    Sevilla                11                 4              1959      H          971 €    NaN       1.0            Grup A
997     Laia   Ferrer Martínez  69760120X       Espanya  Barcelona                11                11              1980      D          682 €    NaN       1.0            Grup A
998    Jordi            García  82947791W       Espanya  Barcelona                23                 5              1984      H        1.699 €    1.0       NaN            Grup C
999    Clara     Sánchez López  89253307W       Espanya     Bilbao                 1                 8              1952      D        1.217 €    NaN       1.0            Grup A

[1000 rows x 13 columns]

In [153]:
#ORDENA POR PAÍS DE ORIGEN. SI EMPATE, POR NOMBRE DE CIUDAD
df_sprint10 = df_sprint10.sort_values(["País d'origen", "Ciutat"]) 
print(df_sprint10.tail(20))

         Nom       Cognoms        DNI País d'origen      Ciutat  Dia de Naixement  Mes de Naixement  Any de Naixement Gènere Salari mensual  Fills  No Fills Grup Professional
311    James         Smith  66434842X    Regne Unit     Londres                 1                 6              1954      H        1.078 €    NaN       1.0            Grup A
362  William   Brown Smith  65737147M    Regne Unit     Londres                17                 7              1959      H        1.147 €    1.0       NaN            Grup A
389   Sophie         Jones  25331092S    Regne Unit     Londres                26                 1              1963      D          684 €    NaN       1.0            Grup A
443     Isla   Brown Jones  58817861M    Regne Unit     Londres                 5                 3              1954      A        2.280 €    1.0       NaN            Grup C
535  William         Brown  16218169P    Regne Unit     Londres                24                 2              1991      H          997 €    1.0       NaN            Grup A
570   Olivia        Taylor  52604206S    Regne Unit     Londres                13                 9              1992     NC        1.416 €    1.0       NaN            Grup A
610     Isla   Smith Brown  96612764F    Regne Unit     Londres                24                 9              1991      D        2.169 €    1.0       NaN            Grup C
724    Emily        Taylor  42592903R    Regne Unit     Londres                24                 3              1976      D        1.250 €    1.0       NaN            Grup A
796  William   Smith Smith  25490219L    Regne Unit     Londres                 1                12              1952      H        1.643 €    1.0       NaN            Grup B
927   Sophie  Taylor Smith  50261072D    Regne Unit     Londres                26                12              2005      D        1.663 €    NaN       1.0            Grup B
930   Sophie         Brown  74953524F    Regne Unit     Londres                17                 5              1983      D        2.189 €    1.0       NaN            Grup C
954     Isla  Taylor Smith  67837921D    Regne Unit     Londres                 7                 5              1965      D        1.237 €    NaN       1.0            Grup A
978  William        Taylor  14371347B    Regne Unit     Londres                11                10              1957      H        1.017 €    NaN       1.0            Grup A
35      Isla         Jones  37846341L    Regne Unit  Manchester                26                 6              1985      D        1.412 €    1.0       NaN            Grup B
222   Sophie         Smith  86350703G    Regne Unit  Manchester                 8                 1              1957      D        1.254 €    1.0       NaN            Grup B
547    Emily  Taylor Jones  89577876S    Regne Unit  Manchester                28                 3              1958      D        2.033 €    NaN       1.0            Grup B
728   George   Brown Jones  57441590Y    Regne Unit  Manchester                27                12              1979      H        1.130 €    1.0       NaN            Grup A
751   Olivia   Brown Brown  58204038A    Regne Unit  Manchester                28                 8              1952      A        1.023 €    NaN       1.0            Grup A
854     Isla   Jones Brown  28367234K    Regne Unit  Manchester                28                 3              1999      D        1.197 €    NaN       1.0            Grup A
872  William         Smith  82046699J    Regne Unit  Manchester                19                 5              1997      H        1.405 €    1.0       NaN            Grup A

In [154]:
# MUESTRA LAS 10 PRIMERAS FILAS:
print(df_sprint10.head(10))

       Nom              Cognoms        DNI País d'origen   Ciutat  Dia de Naixement  Mes de Naixement  Any de Naixement Gènere Salari mensual  Fills  No Fills Grup Professional
21     Mia    Schneider Fischer  28973553Z      Alemanya   Berlín                22                10              1976      A          951 €    NaN       1.0            Grup A
154  Laura    Schneider Fischer  37399141L      Alemanya   Berlín                 2                 2              1958      D        1.769 €    1.0       NaN            Grup B
224    Lea  Schneider Schneider  37368317L      Alemanya   Berlín                23                10              2005      D        2.013 €    NaN       1.0            Grup B
278    Mia              Fischer  21390098Z      Alemanya   Berlín                11                 8              1950      D        1.557 €    1.0       NaN            Grup B
602  Jonas            Schneider  44060014R      Alemanya   Berlín                22                11              1985      H        2.754 €    1.0       NaN            Grup D
871    Lea              Fischer  14773153R      Alemanya   Berlín                 9                 9              1986      D        1.370 €    1.0       NaN            Grup A
281    Lea               Müller  23266650S      Alemanya  Hamburg                14                 4              2003      D        1.314 €    NaN       1.0            Grup A
435   Anna               Müller  83274277X      Alemanya  Hamburg                 1                 1              1987      D        2.464 €    NaN       1.0            Grup C
444  Laura       Schmidt Müller  60161784X      Alemanya  Hamburg                15                 6              1987     NC        2.035 €    1.0       NaN            Grup C
487  Lukas       Müller Fischer  60982309S      Alemanya  Hamburg                28                 3              1971      H        2.042 €    NaN       1.0            Grup B

In [155]:
# MUESTRA SI HAY DUPLICADOS EN DNI

if df_sprint10["DNI"].is_unique:
    print("No hay DNIs duplicados")
else:
    print("Existen DNIs duplicados")
    duplicados = df_sprint10[df_sprint10["DNI"].duplicated(keep=False)] #para ver listados repetidos, incluyendo 1era ocurrencia
    if not duplicados.empty:
        print(duplicados)

No hay DNIs duplicados

#### _1.2_
-Crea una columna que sigui el nom complet.  
-Crea una columna si la persona és nascuda a Espanya o no.  
-Posa el DNI com a índex del DataFrame (noms de files).  
-Substitueix el nom de les columnes Dia de Naixement, Mes de Naixement i Any de Naixement per Dia, Mes i Any.  
-Substitueix H per Home, D per Dona, A per Altres i NC per una dada faltant (nan/null/na).  
-Mostra tots els canvis que has realitzat en una sola taula.

In [ ]:
df_sprint10["Nom complet"] = df_sprint10["Nom"] + " " + df_sprint10["Cognoms"]
df_sprint10

         Nom              Cognoms        DNI País d'origen      Ciutat  Dia de Naixement  Mes de Naixement  Any de Naixement Gènere Salari mensual  Fills  No Fills Grup Professional              Nom complet
21       Mia    Schneider Fischer  28973553Z      Alemanya      Berlín                22                10              1976      A          951 €    NaN       1.0            Grup A    Mia Schneider Fischer
154    Laura    Schneider Fischer  37399141L      Alemanya      Berlín                 2                 2              1958      D        1.769 €    1.0       NaN            Grup B  Laura Schneider Fischer
224      Lea  Schneider Schneider  37368317L      Alemanya      Berlín                23                10              2005      D        2.013 €    NaN       1.0            Grup B  Lea Schneider Schneider
278      Mia              Fischer  21390098Z      Alemanya      Berlín                11                 8              1950      D        1.557 €    1.0       NaN            Grup B              Mia Fischer
602    Jonas            Schneider  44060014R      Alemanya      Berlín                22                11              1985      H        2.754 €    1.0       NaN            Grup D          Jonas Schneider
..       ...                  ...        ...           ...         ...               ...               ...               ...    ...            ...    ...       ...               ...                      ...
547    Emily         Taylor Jones  89577876S    Regne Unit  Manchester                28                 3              1958      D        2.033 €    NaN       1.0            Grup B       Emily Taylor Jones
728   George          Brown Jones  57441590Y    Regne Unit  Manchester                27                12              1979      H        1.130 €    1.0       NaN            Grup A       George Brown Jones
751   Olivia          Brown Brown  58204038A    Regne Unit  Manchester                28                 8              1952      A        1.023 €    NaN       1.0            Grup A       Olivia Brown Brown
854     Isla          Jones Brown  28367234K    Regne Unit  Manchester                28                 3              1999      D        1.197 €    NaN       1.0            Grup A         Isla Jones Brown
872  William                Smith  82046699J    Regne Unit  Manchester                19                 5              1997      H        1.405 €    1.0       NaN            Grup A            William Smith

[1000 rows x 14 columns]

#### _1.3_
Junta las columnas "Fills" y "No Fills" en una sola columna, utilizando el método .apply() y definiendo una función que resuelva el problema. La columna nueva debe llamarse "Hijos" y tomar los valores "Sí" o "No".

**NOTA**: Para comprobar coherencia que cuando Fills tiene valor, columna No fills es NaN, y sacar una lista de los registros contradictorías:  
df_sprint10[(df_sprint10["Fills"] == 1) & (df_sprint10["No Fills"].notna())]

In [157]:
# COMPROBACIONES:
print(df_sprint10[['Fills', 'No Fills']].info())
df_comprobacion = df_sprint10.loc[df_sprint10["Fills"] == 1, "No Fills"].isna().all()
df_comprobacion

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 21 to 872
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Fills     406 non-null    float64
 1   No Fills  594 non-null    float64
dtypes: float64(2)
memory usage: 23.4 KB
None

True

In [158]:
def clasificar_fills_si_no(valores_fila):
    """
    Combina las columnas 'Fills' y 'No Fills' en una sola y actualiza valor según:
    Si valor en 'Fills': "Sí"
    Si valor en 'No Fills': "No"
    Return: str con si o no
    """
    if pd.notnull(valores_fila["Fills"]):
        return "Sí"
    else:
        return "No"

df_sprint10["Fills"] = df_sprint10.apply(clasificar_fills_si_no, axis=1)
df_sprint10 = df_sprint10.drop(columns=["No Fills"])
print(df_sprint10["Fills"].value_counts())
df_sprint10.sample(10)

Fills
No    594
Sí    406
Name: count, dtype: int64

           Nom             Cognoms        DNI País d'origen     Ciutat  Dia de Naixement  Mes de Naixement  Any de Naixement Gènere Salari mensual Fills Grup Professional               Nom complet
31       Oriol        López Ferrer  59690898N       Espanya  Barcelona                 3                11              1969      H        1.498 €    Sí            Grup B        Oriol López Ferrer
164      Salma  Zahraoui El Amrani  89715580M        Marroc      Rabat                28                 9              1950      D        1.141 €    No            Grup A  Salma Zahraoui El Amrani
957       Jean      Girard Lefevre  71514483K        França        Lió                28                12              1960      H          930 €    No            Grup A       Jean Girard Lefevre
138      Chloé              Girard  12234836K        França   Marsella                17                 4              1977      D        1.985 €    Sí            Grup B              Chloé Girard
438      Laura    Schneider Müller  26634596X      Alemanya      Munic                28                11              1990      D        2.778 €    No            Grup D    Laura Schneider Müller
858       Laia              Romero  58632182Z       Espanya    Sevilla                16                11              1962      D        1.211 €    Sí            Grup B               Laia Romero
601        Pau              García  15664344B       Espanya   València                 1                 3              2000      H        2.390 €    No            Grup C                Pau García
795    Camille       Moreau Moreau  93384627N        França        Lió                16                 7              1993      D        1.962 €    No            Grup B     Camille Moreau Moreau
692       Marc              Romero  93864786W       Espanya   València                 8                 6              1957      H          793 €    Sí            Grup A               Marc Romero
409  Francesca             Ferrari  73587985T        Itàlia       Torí                25                 3              1999      D        1.045 €    Sí            Grup A         Francesca Ferrari

#### _1.4_
Crea una taula resum que permeti veure el sou mig, medià, mínim i màxim per Gènere.
Ordena la taula en funció del sou mig.

In [159]:
df_sprint10['Salari mensual'] = df_sprint10['Salari mensual'].str.replace(' €', '').str.replace('.', '').astype(int)

df_resum_salario = (
    df_sprint10
        .groupby("Gènere")["Salari mensual"]
        .agg(
            salario_promedio = "mean",
            mediana_salario  = "median",
            salario_mínimo   = "min",
            salario_máximo   = "max"
        )
)
df_resum_salario = df_resum_salario.round(2)
print(df_resum_salario)

        salario_promedio  mediana_salario  salario_mínimo  salario_máximo
Gènere
A                1626.59           1545.0             703            3175
D                1469.44           1361.5             665            3021
H                1643.25           1531.0             737            3356
NC               1568.87           1443.0             758            2969

#### _1.5_
-Crea una taula resum amb el salari mig per gènere (files) i país d'origen (columnes).  
-Afegeix-hi les mitjanes als marges de la taula.  
(EXTRA): Aplica format condicional a la taula per veure en un color més intens els valors més elevats

In [160]:
df_salario_genero_pais = df_sprint10.pivot_table(
    values="Salari mensual",
    index="Gènere",
    columns="País d'origen",
    aggfunc="mean",
    margins=True,
    margins_name="Promedio_total"
).round(2)

print(df_salario_genero_pais)

País d'origen   Alemanya  Argentina  Colòmbia  Espanya   França   Itàlia   Marroc    Mèxic  Portugal  Regne Unit  Promedio_total
Gènere
A                 951.00    1141.00   1030.00  1706.18      NaN  1423.00  1365.00  1372.00   1765.00     1921.00         1626.59
D                1804.31    1291.80   1497.75  1460.16  1566.47  1247.18  1405.21  1517.80   1488.55     1489.46         1469.44
H                2067.43    1583.29   1554.67  1682.11  1389.25  1672.88  1531.00  1625.00   1497.00     1162.56         1643.25
NC               1931.50    1135.67   1252.00  1597.14  1573.00  1316.00  1365.50  1583.00   1553.50     1758.00         1568.87
Promedio_total   1858.35    1431.68   1489.13  1582.16  1465.36  1421.17  1441.69  1559.08   1527.23     1448.33         1561.46

In [161]:
#EXTRA: formato condicional
df_salario_genero_pais.round(2).style.background_gradient(cmap='YlOrRd').format("{:.2f}")

#### _1.6_
Crea una columna nova que sigui la data de naixament en format Datetime a partir de les columnes dia, mes i any.  
Utilitzant aquesta columna crea una funció que donada una data, et calculi l'edat actual a dia d'avui.  
Utilitza la funció que acabes de crear per generar una columna nova al DataFrame amb l'edat actual.

In [ ]:
from datetime import datetime

df_sprint10['Data Naixement'] = pd.to_datetime(
    df_sprint10[['Any de Naixement', 'Mes de Naixement', 'Dia de Naixement']].rename(
        columns={'Any de Naixement': 'year', 
                 'Mes de Naixement': 'month', 
                 'Dia de Naixement': 'day'}
    )
)

def calcular_edad(fecha_nacimiento):
    hoy = datetime.now()
    edad = hoy.year - fecha_nacimiento.year - (
        (hoy.month, hoy.day) < (fecha_nacimiento.month, fecha_nacimiento.day)
    )
    return edad

df_sprint10['Edat Actual'] = df_sprint10['Data Naixement'].apply(calcular_edad)

print(df_sprint10[['Nom', 'Data Naixement', 'Edat Actual']])

         Nom Data Naixement  Edat Actual
21       Mia     1976-10-22           49
154    Laura     1958-02-02           67
224      Lea     2005-10-23           20
278      Mia     1950-08-11           75
602    Jonas     1985-11-22           40
..       ...            ...          ...
547    Emily     1958-03-28           67
728   George     1979-12-27           46
751   Olivia     1952-08-28           73
854     Isla     1999-03-28           26
872  William     1997-05-19           28

[1000 rows x 3 columns]

# **Nivel 2**

#### 2.1 

-Utilizando el siguiente DataFrame, añade la columna "Incremento" al dataframe del nivel anterior.  
Actualiza la columna salario en función de los porcentajes que se adjuntan.  
df_increment = pd.DataFrame({"Grup":["Grup A","Grup B","Grup C", "Grup D" ] , "Increment":["5%","3,5%","2%","8%"]})

In [163]:
df_increment = pd.DataFrame({
    "Grup":["Grup A","Grup B","Grup C", "Grup D" ],
     "Increment":["5%","3,5%","2%","8%"]
     })

df_increment

     Grup Increment
0  Grup A        5%
1  Grup B      3,5%
2  Grup C        2%
3  Grup D        8%

In [164]:
df_sprint10 = pd.merge(
    df_sprint10,
    df_increment,
    left_on="Grup Professional",
    right_on="Grup",
    how="left"
)

In [ ]:
df_sprint10["Increment_float"] = (
    df_sprint10["Increment"]
        .astype(str)                       
        .str.replace("%", "", regex=False)   
        .str.replace(",", ".", regex=False)  
        .astype(float)                       
        / 100                                
)

df_sprint10["Salari mensual"] = (
    df_sprint10["Salari mensual"]
        .astype(str)                       
        .str.replace(".", "", regex=False)   
        .str.replace(",", ".", regex=False)  
        .str.replace("€", "", regex=False)   
        .str.strip()                         
        .astype(float)
)

df_sprint10["Salari mensual"].dtype
df_sprint10["Increment_float"].dtype

dtype('float64')

In [166]:
df_sprint10["Salari mensual actualizat"] = (df_sprint10["Salari mensual"] * (1 + df_sprint10["Increment_float"])).round(2)

#Se podría borrar la columna "INCREMENT" con el % o dejarla como apoyo visual para informes o visualizaciones.

In [167]:
df_sprint10

         Nom              Cognoms        DNI País d'origen      Ciutat  Dia de Naixement  Mes de Naixement  Any de Naixement Gènere  Salari mensual Fills Grup Professional              Nom complet Data Naixement  Edat Actual    Grup Increment  Increment_float  Salari mensual actualizat
0        Mia    Schneider Fischer  28973553Z      Alemanya      Berlín                22                10              1976      A           951.0    No            Grup A    Mia Schneider Fischer     1976-10-22           49  Grup A        5%            0.050                     998.55
1      Laura    Schneider Fischer  37399141L      Alemanya      Berlín                 2                 2              1958      D          1769.0    Sí            Grup B  Laura Schneider Fischer     1958-02-02           67  Grup B      3,5%            0.035                    1830.92
2        Lea  Schneider Schneider  37368317L      Alemanya      Berlín                23                10              2005      D          2013.0    No            Grup B  Lea Schneider Schneider     2005-10-23           20  Grup B      3,5%            0.035                    2083.46
3        Mia              Fischer  21390098Z      Alemanya      Berlín                11                 8              1950      D          1557.0    Sí            Grup B              Mia Fischer     1950-08-11           75  Grup B      3,5%            0.035                    1611.50
4      Jonas            Schneider  44060014R      Alemanya      Berlín                22                11              1985      H          2754.0    Sí            Grup D          Jonas Schneider     1985-11-22           40  Grup D        8%            0.080                    2974.32
..       ...                  ...        ...           ...         ...               ...               ...               ...    ...             ...   ...               ...                      ...            ...          ...     ...       ...              ...                        ...
995    Emily         Taylor Jones  89577876S    Regne Unit  Manchester                28                 3              1958      D          2033.0    No            Grup B       Emily Taylor Jones     1958-03-28           67  Grup B      3,5%            0.035                    2104.15
996   George          Brown Jones  57441590Y    Regne Unit  Manchester                27                12              1979      H          1130.0    Sí            Grup A       George Brown Jones     1979-12-27           46  Grup A        5%            0.050                    1186.50
997   Olivia          Brown Brown  58204038A    Regne Unit  Manchester                28                 8              1952      A          1023.0    No            Grup A       Olivia Brown Brown     1952-08-28           73  Grup A        5%            0.050                    1074.15
998     Isla          Jones Brown  28367234K    Regne Unit  Manchester                28                 3              1999      D          1197.0    No            Grup A         Isla Jones Brown     1999-03-28           26  Grup A        5%            0.050                    1256.85
999  William                Smith  82046699J    Regne Unit  Manchester                19                 5              1997      H          1405.0    Sí            Grup A            William Smith     1997-05-19           28  Grup A        5%            0.050                    1475.25

[1000 rows x 19 columns]

#### 2.2
Utilizando un bucle, exporta en 4 archivos (formato .xlsx o .csv) los datos de cada Grupo Profesional. Por ejemplo: "datos_GrupA.xlsx" , "datos_GrupB.xlsx" ...

In [ ]:
grupos_profesionales = df_sprint10["Grup Professional"].unique()

for grup in grupos_profesionales:
    df_grupo = df_sprint10[df_sprint10["Grup Professional"] == grup]
    nom_doc = f"datos_{grup}.xlsx"
    df_grupo.to_excel(nom_doc, index=False)
    print(f"Exportado: {nom_doc}")

Exportado: datos Grup A.xlsx
Exportado: datos Grup B.xlsx
Exportado: datos Grup D.xlsx
Exportado: datos Grup C.xlsx

Exporta un 5º DataFrame en formato .xlsx o .csv que contenga cuántos trabajadores hay por cada Grupo Profesional, cuál es su sueldo medio y cuál es su edad media.

In [176]:
resum_grups = df_sprint10.groupby("Grup Professional").agg(
    Num_treballadors=("Nom", "count"),
    Salari_mig=("Salari mensual", "mean"),
    Edat_mitjana=("Edat Actual", "mean")
).reset_index()


resum_grups["Salari_mig"] = resum_grups["Salari_mig"].round(2)
resum_grups["Edat_mitjana"] = resum_grups["Edat_mitjana"].round(0)

resum_grups.columns = ["Grup Professional", "Num de treballadors", "Salari mitjà Eur", "Edat mitjana"]

resum_grups.to_excel("resum_grups_professionals.xlsx", index=False)
resum_grups

  Grup Professional  Num de treballadors  Salari mitjà Eur  Edat mitjana
0            Grup A                  490           1155.55          49.0
1            Grup B                  318           1666.23          48.0
2            Grup C                  137           2244.31          51.0
3            Grup D                   55           2871.13          45.0